version: '3'

services:
  app:
    container_name: appgo.mojotv.cn
    image: hefabao/rdpgo:v0.0.1
    ports:
      - 15081:9528
    restart: always

  # 提供guac 协议
  guacd:
    container_name: guacd.mojotv.cn
    image: guacamole/guacd
    ports:
      - 4822:4822
    restart: always

networks:
  mojo:
    driver: bridge


